### PR TITLE
WebHID integration

### PR DESCRIPTION
**Pull request by JunzheFan**
Hello, to represent the brand of VBet https://en.vbet.cn/, we would like to integrate our current headsets' HID commands into your phone system

### CODE REVIEW

**Comment by JunzheFan** [comment]
@jensengar @maxwellmooney13 hi, have you guys received the samples and managed to do some testings ?

**Comment by JunzheFan** [comment]
thanks x, update me if there's any problem

**Comment by maxwellmooney13** [comment]
Hi @JunzheFan I was able to run through the code on the demo app with the devices you guys sent us.  For the most part things look good, code looks fine as well!  A few things did stand out though and I just wanted to double check with you to ensure I was doing things properly.  1.) What are the gestures to put a call on hold and to reject a call?  I don't believe I have an instruction manual with the devices sent over.  2.) On our application, we offer an option to auto answer incoming calls from a queue for support agents.  On the demo app there is a toggle to somewhat simulate this feature.  It didn't appear that having auto answer on when an incoming call occurs reflected on the device itself.  The green light on the phone button didn't light up to show an active call.

I have a VT USB04 ENC and the VT Lync

**Comment by JunzheFan** [comment]
@maxwellmooney13 hello,  thanks for your time and feedback, we will check those points you mentioned. And for the BT 100U issue, it's a USB dongle that supposed to be paired up with the accompany VT9605 mono headset via bluetooth, after which you can do the HID interaction from the headset,  do you have trouble with the pairing or can you elaborate more about the issues ?

**Comment by maxwellmooney13** [comment]
hi @JunzheFan yeah i was having some difficulty getting the device connected to the dongle.  i'm not sure if i have an instruction booklet for that device... it's possible i might but i have a lot of instruction booklets all over my office.  i can try this again today to see if i can have better success

**Comment by maxwellmooney13** [comment]
hello @JunzheFan I haven't had a chance to try again with the connection but let me take some time now to work on that.  As for the hold not being on every device, that should be fine as I don't remember anything actually breaking during that, it just didn't put the call on hold.  However, if that is known to users who are using your devices, then no issues!

**Comment by JunzheFan** [comment]
@maxwellmooney13 hello, can you manage the test and merge this first version by this month cause some of our customers who are currently using your system would like to give it a try.  BTW, I saw your guys also have a desktop APP for call built with Electron framework, I am not sure how the integration is done there, but I assume this webhid is possible to be transferred to the that Electron-made desktop out of box or you need native some native SDK ?

**Comment by maxwellmooney13** [comment]
hi @JunzheFan yeah i can work on getting these tested and worked out.  Hopefully everything goes smoothly!  As for the desktop app and WebHID capabilities, this is something we've been working on and testing for some time now.  Unfortunately we hit a point where I'm probably not the best person to continue work on it.  The person in mind is even busier than I am though.  So getting WebHID capabilities for our desktop app is definitely on our radar but unsure when we'll really get the ball rolling.

**Comment by maxwellmooney13** [comment]
hi @JunzheFan everything is looking good so far! I pushed up a small change myself that just fixed a failing test.  Functionality is there and looks good, linting is all passing, tests are passing, code looks good.

**Review by maxwellmooney13 — APPROVED** [review]

**Review by jensengar — APPROVED** [review]

**Comment by JunzheFan** [comment]
> hi @JunzheFan everything is looking good so far! I pushed up a small change myself that just fixed a failing test.  Functionality is there and looks good, linting is all passing, tests are passing, code looks good.  Going to get one extra pair of eyes on this to ensure I didn't miss anything in the code.

thank you guys. Please update me whether it's settled and public to production, so that I can signal the end customer to try it

**Comment by maxwellmooney13** [comment]
@JunzheFan We're going to go ahead and merge your PR! However, just so you know, we might not be able to get it to the public until the new year. The reason being is with the holidays coming up, many people will be taking time off (myself included) and we require a good amount of people to properly review new changes.  But once we are all back, we'll take care of getting this released as soon as we can.  Your work on this is done for the time being :) Congrats on the merge!

**Comment by JunzheFan** [comment]
@maxwellmooney13 Appreciate for the time you spent for reviewing ! Btw, can we get an email notification when it's ready or just @ me here cos I am not sure where to track the release progress, do you guys have like a release blog

**Comment by JunzheFan** [comment]
@maxwellmooney13 hello max, hope you had a nice and pleasant Christmas holidays ! !  We are wondering if there is any update/schedule on the release to the production environment of this PR, so that we can update our customers

**Pull request merged**
